#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Cleanly & gracefully kill all tmux open sessions
tmux kill-server 2> /dev/null

# Remove any existing pipe
rm /tmp/bedrock_server_pipe 2> /dev/null || true

# Create pipe
mkfifo /tmp/bedrock_server_pipe

# Change to server directory
cd /opt/minecraft

# Start server
tmux new-session -s bedrock_server -d -n "bedrock_server" "/usr/local/bin/startserver"

# Pipe server output to pipe
tmux pipe-pane -o -t bedrock_server 'cat >> /tmp/bedrock_server_pipe'

# View server output
cat /tmp/bedrock_server_pipe | stdbuf -o0 awk '{print "[bedrock_server] " $0}'

# Exit code matching bedrock_server exit code
exit $(cat /opt/minecraft/.exitcode)
