#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Wait for $BACKUP_FREQUENCY hours
sleep $(expr $BACKUP_FREQUENCY \* 60 \* 60 )

# Run backup
/usr/local/bin/manual_backup 2>&1 | stdbuf -o0 awk '{print "[backup] [" strftime("%Y/%m/%d %H:%M:%S", systime()) " INFO] " $0}'

# Remove old backups
/usr/local/bin/clean_backups 2>&1 | stdbuf -o0 awk '{print "[backup] [" strftime("%Y/%m/%d %H:%M:%S", systime()) " INFO] " $0}'
